/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountData
 */
export interface AccountData {
    /**
     * 
     * @type {User}
     * @memberof AccountData
     */
    user?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AccountData
     */
    roles?: any;
    /**
     * 
     * @type {AccountDataPermissions}
     * @memberof AccountData
     */
    permissions?: any;
    /**
     * 
     * @type {AccountDataViews}
     * @memberof AccountData
     */
    views?: any;
}
