/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Proyecto DIXA API, gestión de documentación
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthUser
 */
export interface AuthUser {
    /**
     * 
     * @type {number}
     * @memberof AuthUser
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    emailVerifiedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    nombre: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    paterno: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    materno: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    celular?: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    imagenFile?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AuthUser
     */
    imagen?: any | null;
    /**
     * 
     * @type {number}
     * @memberof AuthUser
     */
    departamentoId?: any | null;
    /**
     * 
     * @type {AuthUserDepartamento}
     * @memberof AuthUser
     */
    departamento?: any;
}
