/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Auth
 */
export interface Auth {
    /**
     *
     * @type {string}
     * @memberof Auth
     */
    accessToken?: any;
    /**
     *
     * @type {User}
     * @memberof Auth
     */
    user?: any;
    /**
     *
     * @type {string}
     * @memberof Auth
     */
    message?: any;
    /**
     *
     * @type {boolean}
     * @memberof Auth
     */
    success?: any;
    data?: any,
}
