/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Proyecto DIXA API, gestión de documentación
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthUserDepartamento
 */
export interface AuthUserDepartamento {
    /**
     * 
     * @type {number}
     * @memberof AuthUserDepartamento
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AuthUserDepartamento
     */
    nombre?: any;
}
