/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DocumentSimple
 */
export interface DocumentSimple {
    /**
     * 
     * @type {number}
     * @memberof DocumentSimple
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof DocumentSimple
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof DocumentSimple
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof DocumentSimple
     */
    location?: any;
    /**
     * 
     * @type {Date}
     * @memberof DocumentSimple
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof DocumentSimple
     */
    date?: any;
    /**
     * 
     * @type {DocumentType}
     * @memberof DocumentSimple
     */
    type?: any;
    /**
     * 
     * @type {DocumentSimpleParent}
     * @memberof DocumentSimple
     */
    parent?: any;
}
