/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FileMultipartUpdate
 */
export interface FileMultipartUpdate {
    /**
     * 
     * @type {string}
     * @memberof FileMultipartUpdate
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof FileMultipartUpdate
     */
    description: any;
    /**
     * 
     * @type {string}
     * @memberof FileMultipartUpdate
     */
    minIdentifier: any;
    /**
     * 
     * @type {string}
     * @memberof FileMultipartUpdate
     */
    maxIdentifier?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FileMultipartUpdate
     */
    date: any;
    /**
     * 
     * @type {string}
     * @memberof FileMultipartUpdate
     */
    file?: any | null;
    /**
     * 
     * @type {number}
     * @memberof FileMultipartUpdate
     */
    parentId?: any | null;
}
