/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Folder
 */
export interface Folder {
    /**
     *
     * @type {string}
     * @memberof Folder
     */
    name: any;
    /**
     *
     * @type {number}
     * @memberof Folder
     */
    parent_id?: any | null;
}
