/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface History
 */
export interface History {
    /**
     * 
     * @type {number}
     * @memberof History
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof History
     */
    date?: any;
    /**
     * 
     * @type {User}
     * @memberof History
     */
    name?: any;
    /**
     * 
     * @type {Action}
     * @memberof History
     */
    action?: any;
}
