/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {
    /**
     * 
     * @type {InlineResponse20013Data}
     * @memberof InlineResponse20013
     */
    data?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20013
     */
    message?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20013
     */
    success?: any;
}
