/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20013Data
 */
export interface InlineResponse20013Data {
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof InlineResponse20013Data
     */
    attached?: any;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof InlineResponse20013Data
     */
    detached?: any;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof InlineResponse20013Data
     */
    updated?: any;
}
