/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 
     * @type {Role}
     * @memberof InlineResponse2005
     */
    data?: any;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005
     */
    message?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2005
     */
    success?: any;
}
