/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Proyecto DIXA API, gestión de documentación
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse401
 */
export interface InlineResponse401 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse401
     */
    errors?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse401
     */
    success?: any;
}
