/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdatePassword
 */
export interface UpdatePassword {
    /**
     * 
     * @type {string}
     * @memberof UpdatePassword
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePassword
     */
    passwordConfirmation: any;
    /**
     * 
     * @type {string}
     * @memberof UpdatePassword
     */
    newPassword: any;
}
