/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserMultipartUpdate
 */
export interface UserMultipartUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    lastname: any;
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    secondLastname: any;
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    phone: any;
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof UserMultipartUpdate
     */
    imageFile?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserMultipartUpdate
     */
    roleId: any;
    /**
     * 
     * @type {number}
     * @memberof UserMultipartUpdate
     */
    departmentId?: any | null;
}
