/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    emailVerifiedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastname?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    secondLastname?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    image?: any;
    /**
     * 
     * @type {Role}
     * @memberof User
     */
    role?: any;
    /**
     * 
     * @type {Department}
     * @memberof User
     */
    department?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof User
     */
    authorization?: any;
}
