/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/admin-api';
export * from './apis/auth-api';
export * from './apis/departments-api';
export * from './apis/documents-api';
export * from './apis/permissions-api';
export * from './apis/roles-api';
export * from './apis/share-document-api';
export * from './apis/share-document-user-api';
export * from './apis/users-api';

