/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ // @ts-ignore
export * from './apis/admin-api';
// @ts-ignore
export * from './apis/auth-api';
// @ts-ignore
export * from './apis/departments-api';
// @ts-ignore
export * from './apis/roles-api';
// @ts-ignore
export * from './apis/users-api';

