/* tslint:disable */
/* eslint-disable */
/**
 * DIXA API
 * Project DIXA API, documentation management
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DocumentIdRenameBody } from '../models';
import { DocumentIdTagsBody } from '../models';
import { InlineResponse20010 } from '../models';
import { InlineResponse2008 } from '../models';
import { InlineResponse2009 } from '../models';
import { InlineResponse400 } from '../models';
import { InlineResponse401 } from '../models';
import { InlineResponse403 } from '../models';
import { InlineResponse404 } from '../models';
import { InlineResponse422 } from '../models';
/**
 * DocumentsApi - axios parameter creator
 * @export
 */
export const DocumentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * create a folder in the system
         * @summary Create - Folder
         * @param {string} [name] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocumentFolder: async (name?: string, parentId?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/folders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication bearerAuth required


            if (name !== undefined) { 
                localVarFormParams.append('name', name as any);
            }

            if (parentId !== undefined) { 
                localVarFormParams.append('parent_id', parentId as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * create a document in the system
         * @summary Create - File
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [minIdentifier] 
         * @param {string} [maxIdentifier] 
         * @param {string} [date] 
         * @param {string} [file] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFile: async (name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/documents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication bearerAuth required


            if (name !== undefined) { 
                localVarFormParams.append('name', name as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }

            if (minIdentifier !== undefined) { 
                localVarFormParams.append('min_identifier', minIdentifier as any);
            }

            if (maxIdentifier !== undefined) { 
                localVarFormParams.append('max_identifier', maxIdentifier as any);
            }

            if (date !== undefined) { 
                localVarFormParams.append('date', date as any);
            }

            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            if (parentId !== undefined) { 
                localVarFormParams.append('parent_id', parentId as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete the document in a single request
         * @summary Delete - Document
         * @param {number} documentId document id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDocument: async (documentId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling deleteDocument.');
            }
            const localVarPath = `/documents/{document_id}`
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete tag of document in a single request
         * @summary Delete - Document Tags
         * @param {number} documentId document id
         * @param {string} tagName tag name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDocumentTags: async (documentId: number, tagName: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling deleteDocumentTags.');
            }
            // verify required parameter 'tagName' is not null or undefined
            if (tagName === null || tagName === undefined) {
                throw new RequiredError('tagName','Required parameter tagName was null or undefined when calling deleteDocumentTags.');
            }
            const localVarPath = `/documents/{document_id}/tags/{tag_name}`
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"tag_name"}}`, encodeURIComponent(String(tagName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the document in a single request
         * @summary Get - Document
         * @param {number} documentId document id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocument: async (documentId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling getDocument.');
            }
            const localVarPath = `/documents/{document_id}`
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the list of all documents in a single request
         * @summary List - Documents
         * @param {number} [parent] (folder id) Value get files from parent folder
         * @param {string} [name] Value to filter by name of document
         * @param {boolean} [all] if this value is true, it will search in all the user&#x27;s documents, if it is false, it will search in its respective level
         * @param {string} [type] search by folder or file, allowed values are Carpeta and Archivo
         * @param {Array&lt;string&gt;} [tags] an array of tags
         * @param {Array&lt;number&gt;} [identifiers] an array of folios
         * @param {string} [startDate] search date
         * @param {string} [endDate] search date
         * @param {number} [page] page to query
         * @param {number} [perPage] number of items you want the response to return
         * @param {string} [sortBy] field by which you want to sort
         * @param {string} [order] sort type, descending or ascending
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocuments: async (parent?: number, name?: string, all?: boolean, type?: string, tags?: Array<string>, identifiers?: Array<number>, startDate?: string, endDate?: string, page?: number, perPage?: number, sortBy?: string, order?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/documents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            if (parent !== undefined) {
                localVarQueryParameter['parent'] = parent;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (all !== undefined) {
                localVarQueryParameter['all'] = all;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (tags) {
                localVarQueryParameter['tags[]'] = tags;
            }

            if (identifiers) {
                localVarQueryParameter['identifiers[]'] = identifiers;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substr(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substr(0,10) :
                    endDate;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['perPage'] = perPage;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Rename the document in a single request
         * @summary Rename - Document
         * @param {number} documentId document id
         * @param {DocumentIdRenameBody} [body] Request in format json format
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renameDocument: async (documentId: number, body?: DocumentIdRenameBody, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling renameDocument.');
            }
            const localVarPath = `/documents/{document_id}/:rename`
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Save tags of document in a single request
         * @summary Save - Document Tags
         * @param {number} documentId document id
         * @param {DocumentIdTagsBody} [body] Request in format json format
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveDocumentTags: async (documentId: number, body?: DocumentIdTagsBody, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling saveDocumentTags.');
            }
            const localVarPath = `/documents/{document_id}/tags`
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * update a document in the system
         * @summary Update - File
         * @param {number} documentId document id
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [minIdentifier] 
         * @param {string} [maxIdentifier] 
         * @param {string} [date] 
         * @param {string} [file] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateFile: async (documentId: number, name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling updateFile.');
            }
            const localVarPath = `/documents/{document_id}`
                .replace(`{${"document_id"}}`, encodeURIComponent(String(documentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication bearerAuth required


            if (name !== undefined) { 
                localVarFormParams.append('name', name as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }

            if (minIdentifier !== undefined) { 
                localVarFormParams.append('min_identifier', minIdentifier as any);
            }

            if (maxIdentifier !== undefined) { 
                localVarFormParams.append('max_identifier', maxIdentifier as any);
            }

            if (date !== undefined) { 
                localVarFormParams.append('date', date as any);
            }

            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            if (parentId !== undefined) { 
                localVarFormParams.append('parent_id', parentId as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentsApi - functional programming interface
 * @export
 */
export const DocumentsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * create a folder in the system
         * @summary Create - Folder
         * @param {string} [name] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDocumentFolder(name?: string, parentId?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).createDocumentFolder(name, parentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * create a document in the system
         * @summary Create - File
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [minIdentifier] 
         * @param {string} [maxIdentifier] 
         * @param {string} [date] 
         * @param {string} [file] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createFile(name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).createFile(name, description, minIdentifier, maxIdentifier, date, file, parentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete the document in a single request
         * @summary Delete - Document
         * @param {number} documentId document id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDocument(documentId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse20010>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).deleteDocument(documentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete tag of document in a single request
         * @summary Delete - Document Tags
         * @param {number} documentId document id
         * @param {string} tagName tag name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDocumentTags(documentId: number, tagName: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).deleteDocumentTags(documentId, tagName, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the document in a single request
         * @summary Get - Document
         * @param {number} documentId document id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDocument(documentId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).getDocument(documentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the list of all documents in a single request
         * @summary List - Documents
         * @param {number} [parent] (folder id) Value get files from parent folder
         * @param {string} [name] Value to filter by name of document
         * @param {boolean} [all] if this value is true, it will search in all the user&#x27;s documents, if it is false, it will search in its respective level
         * @param {string} [type] search by folder or file, allowed values are Carpeta and Archivo
         * @param {Array&lt;string&gt;} [tags] an array of tags
         * @param {Array&lt;number&gt;} [identifiers] an array of folios
         * @param {string} [startDate] search date
         * @param {string} [endDate] search date
         * @param {number} [page] page to query
         * @param {number} [perPage] number of items you want the response to return
         * @param {string} [sortBy] field by which you want to sort
         * @param {string} [order] sort type, descending or ascending
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDocuments(parent?: number, name?: string, all?: boolean, type?: string, tags?: Array<string>, identifiers?: Array<number>, startDate?: string, endDate?: string, page?: number, perPage?: number, sortBy?: string, order?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2008>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).getDocuments(parent, name, all, type, tags, identifiers, startDate, endDate, page, perPage, sortBy, order, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Rename the document in a single request
         * @summary Rename - Document
         * @param {number} documentId document id
         * @param {DocumentIdRenameBody} [body] Request in format json format
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renameDocument(documentId: number, body?: DocumentIdRenameBody, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).renameDocument(documentId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Save tags of document in a single request
         * @summary Save - Document Tags
         * @param {number} documentId document id
         * @param {DocumentIdTagsBody} [body] Request in format json format
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveDocumentTags(documentId: number, body?: DocumentIdTagsBody, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).saveDocumentTags(documentId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * update a document in the system
         * @summary Update - File
         * @param {number} documentId document id
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [minIdentifier] 
         * @param {string} [maxIdentifier] 
         * @param {string} [date] 
         * @param {string} [file] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateFile(documentId: number, name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2009>> {
            const localVarAxiosArgs = await DocumentsApiAxiosParamCreator(configuration).updateFile(documentId, name, description, minIdentifier, maxIdentifier, date, file, parentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DocumentsApi - factory interface
 * @export
 */
export const DocumentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * create a folder in the system
         * @summary Create - Folder
         * @param {string} [name] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocumentFolder(name?: string, parentId?: number, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).createDocumentFolder(name, parentId, options).then((request) => request(axios, basePath));
        },
        /**
         * create a document in the system
         * @summary Create - File
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [minIdentifier] 
         * @param {string} [maxIdentifier] 
         * @param {string} [date] 
         * @param {string} [file] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFile(name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).createFile(name, description, minIdentifier, maxIdentifier, date, file, parentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete the document in a single request
         * @summary Delete - Document
         * @param {number} documentId document id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDocument(documentId: number, options?: any): AxiosPromise<InlineResponse20010> {
            return DocumentsApiFp(configuration).deleteDocument(documentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete tag of document in a single request
         * @summary Delete - Document Tags
         * @param {number} documentId document id
         * @param {string} tagName tag name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDocumentTags(documentId: number, tagName: string, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).deleteDocumentTags(documentId, tagName, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the document in a single request
         * @summary Get - Document
         * @param {number} documentId document id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocument(documentId: number, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).getDocument(documentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the list of all documents in a single request
         * @summary List - Documents
         * @param {number} [parent] (folder id) Value get files from parent folder
         * @param {string} [name] Value to filter by name of document
         * @param {boolean} [all] if this value is true, it will search in all the user&#x27;s documents, if it is false, it will search in its respective level
         * @param {string} [type] search by folder or file, allowed values are Carpeta and Archivo
         * @param {Array&lt;string&gt;} [tags] an array of tags
         * @param {Array&lt;number&gt;} [identifiers] an array of folios
         * @param {string} [startDate] search date
         * @param {string} [endDate] search date
         * @param {number} [page] page to query
         * @param {number} [perPage] number of items you want the response to return
         * @param {string} [sortBy] field by which you want to sort
         * @param {string} [order] sort type, descending or ascending
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocuments(parent?: number, name?: string, all?: boolean, type?: string, tags?: Array<string>, identifiers?: Array<number>, startDate?: string, endDate?: string, page?: number, perPage?: number, sortBy?: string, order?: string, options?: any): AxiosPromise<InlineResponse2008> {
            return DocumentsApiFp(configuration).getDocuments(parent, name, all, type, tags, identifiers, startDate, endDate, page, perPage, sortBy, order, options).then((request) => request(axios, basePath));
        },
        /**
         * Rename the document in a single request
         * @summary Rename - Document
         * @param {number} documentId document id
         * @param {DocumentIdRenameBody} [body] Request in format json format
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renameDocument(documentId: number, body?: DocumentIdRenameBody, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).renameDocument(documentId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Save tags of document in a single request
         * @summary Save - Document Tags
         * @param {number} documentId document id
         * @param {DocumentIdTagsBody} [body] Request in format json format
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveDocumentTags(documentId: number, body?: DocumentIdTagsBody, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).saveDocumentTags(documentId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * update a document in the system
         * @summary Update - File
         * @param {number} documentId document id
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [minIdentifier] 
         * @param {string} [maxIdentifier] 
         * @param {string} [date] 
         * @param {string} [file] 
         * @param {number} [parentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateFile(documentId: number, name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options?: any): AxiosPromise<InlineResponse2009> {
            return DocumentsApiFp(configuration).updateFile(documentId, name, description, minIdentifier, maxIdentifier, date, file, parentId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DocumentsApi - object-oriented interface
 * @export
 * @class DocumentsApi
 * @extends {BaseAPI}
 */
export class DocumentsApi extends BaseAPI {
    /**
     * create a folder in the system
     * @summary Create - Folder
     * @param {string} [name] 
     * @param {number} [parentId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public createDocumentFolder(name?: string, parentId?: number, options?: any) {
        return DocumentsApiFp(this.configuration).createDocumentFolder(name, parentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * create a document in the system
     * @summary Create - File
     * @param {string} [name] 
     * @param {string} [description] 
     * @param {string} [minIdentifier] 
     * @param {string} [maxIdentifier] 
     * @param {string} [date] 
     * @param {string} [file] 
     * @param {number} [parentId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public createFile(name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options?: any) {
        return DocumentsApiFp(this.configuration).createFile(name, description, minIdentifier, maxIdentifier, date, file, parentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete the document in a single request
     * @summary Delete - Document
     * @param {number} documentId document id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public deleteDocument(documentId: number, options?: any) {
        return DocumentsApiFp(this.configuration).deleteDocument(documentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete tag of document in a single request
     * @summary Delete - Document Tags
     * @param {number} documentId document id
     * @param {string} tagName tag name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public deleteDocumentTags(documentId: number, tagName: string, options?: any) {
        return DocumentsApiFp(this.configuration).deleteDocumentTags(documentId, tagName, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the document in a single request
     * @summary Get - Document
     * @param {number} documentId document id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public getDocument(documentId: number, options?: any) {
        return DocumentsApiFp(this.configuration).getDocument(documentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the list of all documents in a single request
     * @summary List - Documents
     * @param {number} [parent] (folder id) Value get files from parent folder
     * @param {string} [name] Value to filter by name of document
     * @param {boolean} [all] if this value is true, it will search in all the user&#x27;s documents, if it is false, it will search in its respective level
     * @param {string} [type] search by folder or file, allowed values are Carpeta and Archivo
     * @param {Array&lt;string&gt;} [tags] an array of tags
     * @param {Array&lt;number&gt;} [identifiers] an array of folios
     * @param {string} [startDate] search date
     * @param {string} [endDate] search date
     * @param {number} [page] page to query
     * @param {number} [perPage] number of items you want the response to return
     * @param {string} [sortBy] field by which you want to sort
     * @param {string} [order] sort type, descending or ascending
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public getDocuments(parent?: number, name?: string, all?: boolean, type?: string, tags?: Array<string>, identifiers?: Array<number>, startDate?: string, endDate?: string, page?: number, perPage?: number, sortBy?: string, order?: string, options?: any) {
        return DocumentsApiFp(this.configuration).getDocuments(parent, name, all, type, tags, identifiers, startDate, endDate, page, perPage, sortBy, order, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Rename the document in a single request
     * @summary Rename - Document
     * @param {number} documentId document id
     * @param {DocumentIdRenameBody} [body] Request in format json format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public renameDocument(documentId: number, body?: DocumentIdRenameBody, options?: any) {
        return DocumentsApiFp(this.configuration).renameDocument(documentId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Save tags of document in a single request
     * @summary Save - Document Tags
     * @param {number} documentId document id
     * @param {DocumentIdTagsBody} [body] Request in format json format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public saveDocumentTags(documentId: number, body?: DocumentIdTagsBody, options?: any) {
        return DocumentsApiFp(this.configuration).saveDocumentTags(documentId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * update a document in the system
     * @summary Update - File
     * @param {number} documentId document id
     * @param {string} [name] 
     * @param {string} [description] 
     * @param {string} [minIdentifier] 
     * @param {string} [maxIdentifier] 
     * @param {string} [date] 
     * @param {string} [file] 
     * @param {number} [parentId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DocumentsApi
     */
    public updateFile(documentId: number, name?: string, description?: string, minIdentifier?: string, maxIdentifier?: string, date?: string, file?: string, parentId?: number, options?: any) {
        return DocumentsApiFp(this.configuration).updateFile(documentId, name, description, minIdentifier, maxIdentifier, date, file, parentId, options).then((request) => request(this.axios, this.basePath));
    }
}
